Диплом. Этап 1. Сервис статистики.
FedoRScorpioN/java-explore-with-me pull request #2
Opened 2023-03-15 11:16 UTC by FedoRScorpioN

2023-03-16 07:51 UTC, LexLippi requested changes
Привет!

Хорошая работа, но есть некоторое количество замечаний, которое надо поправить!

Желаю удачи!

2023-03-16 07:51 UTC, LexLippi commented on docker-compose.yml
> +      - SPRING_DATASOURCE_PASSWORD=password
Здесь переделывать ничего не нужно, иначе `Postman`-тесты повалятся, но так в реальности никто не делает, такие данные люди хранят в `.env`-файлах.

Которые либо шифруют, либо вообще не складывают в репозиторий, иначе это небезопасно :(

2023-03-16 07:51 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/EwmApplication.java
> +public class EwmApplication {
А что такое `Ewm`?

2023-03-16 07:51 UTC, LexLippi commented on ewm/src/main/resources/application.properties
> +#spring.application.name=EwmApplication
комментарии не храним

2023-03-16 07:51 UTC, LexLippi commented on ewm/src/main/resources/application.properties
> +spring.datasource.password=password
в открытом виде в репозитории эти данные никто не хранит, но это опять же на будущее :)

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/stats/client/StatsClient.java
> +    private final String application;
Если там действительно `URL` лежит, то лучше пользоваться `java.net.URI` и называть эту переменную `applicationUrl`

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/stats/client/StatsClient.java
> +    private final String statsServiceUri;
Аналогично тому, что выше написал, если это полный `URL`

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/stats/client/StatsClient.java
> +    private final ObjectMapper json;
Ну это всё-таки не `json`, а `jsonMapper`

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/server/controller/StatsController.java
> +            @RequestParam(defaultValue = "false") Boolean unique) {
может тогда `boolean`, если он `null` значения не принимает?

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/server/controller/StatsController.java
> +    public void saveHit(@RequestBody @Valid EndpointHitDto hitDto) {
Может просто `hitDto`,  причем тут эндпоинт я не очень понимаю :)

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/server/controller/StatsController.java
> +@RequestMapping(path = "")
Кажется и без явного указания пути должно корректно работать.

Тут можно увидеть, какое значение по умолчанию принимает эта переменная:
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestMapping.html#path()

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/server/controller/StatsController.java
> +@Slf4j
Зачем тебе `Slf4j`, если ты им не пользуешься?

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/server/mapper/EndpointHitMapper.java
> +public class EndpointHitMapper {
1. Если мы не хотим, чтобы у кого-то была возможность переопределить этот класс, то лучше делать его `final`
2. Чаще всего мы хотим, что объект-маппер был синглтоном:
https://en.wikipedia.org/wiki/Singleton_pattern
3. Проще всего добиться выполнения пункта 2 с помощью `enum`:
https://www.geeksforgeeks.org/advantages-and-disadvantages-of-using-enum-as-singleton-in-java/

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/server/model/EndpointHit.java
> +    String ip;
А почему не все `NotBlank` адаптации в этот объект переехали из `EndpointHitDto`?

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/server/model/EndpointHit.java
> +    @Column(length = 255)
Даже `ipv6`-адрес это не больше 46 символов, а `ipv4` не больше 15, так что 255 это сильно с запасом

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/stats/server/service/StatsServiceImpl.java
> +    public List<ViewStatsDto> getViewStats(LocalDateTime start, LocalDateTime end, String[] uris, Boolean unique) {
Все операторы `else` в этом методе бессмысленны, так как ты везде до этого `return` делаешь.
Можно уменьшить цикломатическую сложность избавившись от них

2023-03-16 07:51 UTC, LexLippi commented on stats/stats-server/src/main/resources/schema.sql
> +    TIMESTAMP TIMESTAMP WITHOUT TIME ZONE NOT NULL
Не стоит называть колонку также, как и тип данных.

Здесь есть хороший коммент почему так делать не стоит
https://stackoverflow.com/questions/20012586/sql-column-names-same-as-names-for-data-types-causing-errors

2023-03-16 07:56 UTC, FedoRScorpioN commented on docker-compose.yml
> +      - SPRING_DATASOURCE_PASSWORD=password
Тесты они такие...

2023-03-16 07:58 UTC, FedoRScorpioN commented on ewm/src/main/java/ru/practicum/ewm/EwmApplication.java
> +public class EwmApplication {
Сокращённое название всего проекта - **E**xplore-**W**ith-**M**e - сокращённо EWM (по первым буквам).

2023-03-16 08:00 UTC, FedoRScorpioN commented on ewm/src/main/resources/application.properties
> +#spring.application.name=EwmApplication
Помню.
Есть какой-нибудь плагин для IDEA или хоткей, который позволяет очистить весь проект от комментов автоматически? Для меня удобно ими пользоваться в процессе работы, а потом приходится вручную убирать. Иногда остаются...(((

2023-03-16 08:16 UTC, FedoRScorpioN commented on stats/stats-client/src/main/java/ru/practicum/stats/client/StatsClient.java
> +    private final ObjectMapper json;
Исправил.

2023-03-16 08:35 UTC, FedoRScorpioN commented on stats/stats-client/src/main/java/ru/practicum/stats/client/StatsClient.java
> +    private final String application;
Исправил.

2023-03-16 08:35 UTC, FedoRScorpioN commented on stats/stats-client/src/main/java/ru/practicum/stats/client/StatsClient.java
> +    private final String statsServiceUri;
Исправил.

2023-03-16 08:45 UTC, FedoRScorpioN commented on stats/stats-server/src/main/java/ru/practicum/stats/server/controller/StatsController.java
> +            @RequestParam(defaultValue = "false") Boolean unique) {
Понял. Исправил.

2023-03-16 09:05 UTC, FedoRScorpioN commented on stats/stats-server/src/main/java/ru/practicum/stats/server/controller/StatsController.java
> +    public void saveHit(@RequestBody @Valid EndpointHitDto hitDto) {
Логика нейминга классов была следующая:
Если у нас есть EndpointHit (из спецификации к ТЗ), то DTO для него - EndpointHitDto.

2023-03-16 09:08 UTC, FedoRScorpioN commented on stats/stats-server/src/main/java/ru/practicum/stats/server/controller/StatsController.java
> +@RequestMapping(path = "")
Понял. Подправил.

2023-03-16 09:08 UTC, FedoRScorpioN commented on stats/stats-server/src/main/java/ru/practicum/stats/server/controller/StatsController.java
> +@Slf4j
Убрал.

2023-03-16 09:28 UTC, FedoRScorpioN commented on stats/stats-server/src/main/java/ru/practicum/stats/server/mapper/EndpointHitMapper.java
> +public class EndpointHitMapper {
Переделал этот класс в интерфейс. Получилось лаконичнее. п. 2 - выполнил.

2023-03-16 09:29 UTC, FedoRScorpioN commented on stats/stats-server/src/main/java/ru/practicum/stats/server/model/EndpointHit.java
> +    String ip;
Исправил.

2023-03-16 09:29 UTC, FedoRScorpioN commented on stats/stats-server/src/main/java/ru/practicum/stats/server/model/EndpointHit.java
> +    @Column(length = 255)
Подправил.

2023-03-16 09:37 UTC, FedoRScorpioN commented on stats/stats-server/src/main/java/ru/practicum/stats/server/service/StatsServiceImpl.java
> +    public List<ViewStatsDto> getViewStats(LocalDateTime start, LocalDateTime end, String[] uris, Boolean unique) {
Убрал лишнее.

2023-03-16 09:58 UTC, FedoRScorpioN commented on stats/stats-server/src/main/resources/schema.sql
> +    TIMESTAMP TIMESTAMP WITHOUT TIME ZONE NOT NULL
Алексей, я помню твои замечания по предыдущим Спринтам. Но, к сожалению, не могу объяснить это тестам (или ещё не умею обходить эти подводные камни), они падают если наименование отличается от указанной в спецификации. Может есть какая-то возможность переименовать колонку в таблице и при этом сделать чтобы тесты не падали?

Конструкция
    @Column(name = "TIME_REQUEST", updatable = false)
    LocalDateTime timestamp;
    
    Результатов не даёт.

2023-03-16 09:59 UTC, FedoRScorpioN commented on stats/stats-server/src/main/resources/schema.sql
> +    TIMESTAMP TIMESTAMP WITHOUT TIME ZONE NOT NULL
Хотя это может быть как в прошлый раз и падают только локальные. Сейчас попробую на ГитХабе пройти.

2023-03-17 07:00 UTC, LexLippi commented on ewm/src/main/resources/application.properties
> +#spring.application.name=EwmApplication
Есть плагины и разные настройки в идеа, но там сложно одновременно все типы комментариев настроить, но можно попробовать:

https://stackoverflow.com/questions/2613432/remove-source-file-comments-using-intellij

2023-03-17 07:01 UTC, LexLippi commented on stats/stats-server/src/main/resources/schema.sql
> +    TIMESTAMP TIMESTAMP WITHOUT TIME ZONE NOT NULL
Ага, ну там по ссылке, которую я скинул люди советую хотя бы кавычками это дело обрамлять  вот такими `, это вроде может поможет избавиться от некоторых проблем

2023-03-17 07:04 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих этапах дипломного проекта!

2023-03-17 07:04 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих этапах дипломного проекта!

2023-03-17 09:10 UTC, merged