Диплом. Этап 2. Основной сервис.
FedoRScorpioN/java-explore-with-me pull request #4
Opened 2023-03-21 23:51 UTC by FedoRScorpioN

2023-03-22 07:24 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!
Желаю удачи!!!

2023-03-22 07:24 UTC, LexLippi commented on ewm/pom.xml
> +<!--    <description>ewm</description>-->
А почему закомментил это?

2023-03-22 07:24 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/category/Categories.java
> +    private String name;
Может стоит поставить, какие-то разумные ограничения на размер названия?

2023-03-22 07:24 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/category/CategoriesServiceImpl.java
> +        Categories createdCategories;
Всегда советую не заводить не инициализированные переменные. Во-первых, если метод разрастается, то это сложно читать и работать с этим. Во-вторых это может породить неконтролирумые `null`, что вообще очень плохо и может неожиданно выстрелить в ногу.

Здесь кажется вполне можно обойтись без этого, так как в блоке `catch` ты перевыбрасываешь исключение, то `return` можно делать внутри `try`. К тому же, это заставляет подумать о том, что может произойти `NPE`, в случае если произошло другое исключение, а не `DataIntegrityViolationException`.

2023-03-22 07:24 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/category/CategoriesServiceImpl.java
> +        Pageable pageable = PageRequest.of(from, size);
А зачем отдельную локальную переменную под это заводить, кажется, что она дает не сильно много дополнительной информации, и используется только однажды

2023-03-22 07:24 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/category/CategoriesServiceImpl.java
> +    public CategoriesDto updateCategory(Long id, NewCategoriesDto categoryDto) {
Аналогично тому, что выше написал

2023-03-22 07:24 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/category/NewCategoriesDto.java
> +}
А это точно необходимо? Нельзя использовать другое `dto`, просто не заполняя `id`?

2023-03-22 07:24 UTC, LexLippi commented on stats/stats-server/pom.xml
> +<!--        </dependency>-->
Удалить, если не нужно

2023-03-22 07:24 UTC, LexLippi commented on stats/stats-server/pom.xml
> +<!--    <description>stats-service</description>-->
Или удалить, или раскомментировать

2023-03-22 07:24 UTC, LexLippi commented on ewm/src/main/resources/application.properties
> +#stats-server.url=http://stats-server:9090
?
Удалить все, если не нужно

2023-03-22 07:24 UTC, LexLippi commented on ewm/src/main/resources/schema.sql
> +    EMAIL VARCHAR(255) NOT NULL UNIQUE
По RFC `email` может занимать 320 символов, так что лучше сразу ткую длину и использовать:

https://www.rfc-editor.org/errata/eid1690

2023-03-22 07:24 UTC, LexLippi commented on ewm/src/main/resources/schema.sql
> +    REQUEST_MODERATION BOOLEAN,
Может быть `NULL`? Явно можно добавить ограничение.
Насчет строки выше тоже подумай

2023-03-22 07:24 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/user/UsersServiceImpl.java
> +        return newUser;
Можем вернуть `null`. Это ок?

2023-03-22 07:24 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/user/UsersServiceImpl.java
> +        } else {
Если в условном операторе есть `return`, то `else` не нужен

2023-03-22 07:32 UTC, FedoRScorpioN commented on ewm/pom.xml
> +<!--    <description>ewm</description>-->
Не убрал со времён экспериментов с POMами. Поправил.

2023-03-22 07:34 UTC, FedoRScorpioN commented on ewm/src/main/java/ru/practicum/ewm/category/Categories.java
> +    private String name;
Исправил.

2023-03-22 07:41 UTC, FedoRScorpioN commented on ewm/src/main/java/ru/practicum/ewm/category/CategoriesServiceImpl.java
> +        Categories createdCategories;
Подправил.

2023-03-22 07:44 UTC, FedoRScorpioN commented on ewm/src/main/java/ru/practicum/ewm/category/CategoriesServiceImpl.java
> +        Pageable pageable = PageRequest.of(from, size);
Согласен. В процессе метод был оптимизирован и сократился от изначального варианта. Исправил.

2023-03-22 07:47 UTC, FedoRScorpioN commented on ewm/src/main/java/ru/practicum/ewm/category/CategoriesServiceImpl.java
> +    public CategoriesDto updateCategory(Long id, NewCategoriesDto categoryDto) {
Исправил.

2023-03-22 07:49 UTC, FedoRScorpioN commented on ewm/src/main/resources/application.properties
> +#stats-server.url=http://stats-server:9090
Согласен. Исправил.

2023-03-22 07:50 UTC, FedoRScorpioN commented on ewm/src/main/resources/schema.sql
> +    EMAIL VARCHAR(255) NOT NULL UNIQUE
Не знал. Спасибо за информацию. Поправил.

2023-03-22 08:06 UTC, FedoRScorpioN commented on ewm/src/main/resources/schema.sql
> +    REQUEST_MODERATION BOOLEAN,
Согласен. Если PARTICIPANT_LIMIT равно 0 (что должно быть явно указано), то ограничение на количество участников отсутствует.
Аналогично для колонки DESCRIPTION сделал. 
А вот время публикации, согласно логике, при создании События может быть равно 0. Так как мы его можем создать, но не опубликовать сразу.

2023-03-22 09:42 UTC, FedoRScorpioN commented on ewm/src/main/java/ru/practicum/ewm/category/NewCategoriesDto.java
> +}
Пробовал изначально сделать вот так:
@PostMapping
@ResponseStatus(HttpStatus.CREATED)
public CategoriesDto createCategory(@RequestBody @Valid CategoriesDto categoriesDto, HttpServletRequest request) {
    categoriesDto.setId(null);
    log.info("{}", ControllerLog.createUrlInfo(request));
    return categoriesService.addCategory(categoriesDto);
}

Начинают тесты сыпаться, поэтому сделал дополнительный ДТО. Работает))))

2023-03-22 09:43 UTC, FedoRScorpioN commented on stats/stats-server/pom.xml
> +<!--        </dependency>-->
Исправил

2023-03-22 09:43 UTC, FedoRScorpioN commented on stats/stats-server/pom.xml
> +<!--    <description>stats-service</description>-->
Исправил все комменты.

2023-03-22 09:52 UTC, FedoRScorpioN commented on ewm/src/main/java/ru/practicum/ewm/user/UsersServiceImpl.java
> +        return newUser;
Совсем не Ок. Добавил проверку.

2023-03-22 09:57 UTC, FedoRScorpioN commented on ewm/src/main/java/ru/practicum/ewm/user/UsersServiceImpl.java
> +        } else {
Исправил.

2023-03-23 07:46 UTC, LexLippi commented on ewm/src/main/resources/schema.sql
> +    EMAIL VARCHAR(255) NOT NULL UNIQUE
Ну я так понимаю, что это просто ограничения одного из почтовых клиентов. Ничего не мешает человеку написать свой почтовый клиент (часто, кстати так люди делают). Главное, что больше, чем по RFC это просто ни один сервер принимать не сможет, а все, что укладывается в ограничения могут отклонять некоторые сервера, но в целом это будет работать :)

2023-03-23 07:48 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи с последним этапом диплома!!!

2023-03-23 09:00 UTC, merged