Диплом. Этап 3. Дополнительная функциональность (комментарии).
FedoRScorpioN/java-explore-with-me pull request #5
Opened 2023-03-23 22:30 UTC by FedoRScorpioN

Added functionality "Comments".

2023-03-27 20:35 UTC, LexLippi requested changes
Привет!

Замечательная работа!

Но есть пару замечаний, которые хотелось бы увидеть исправленными!
Желаю удачи!

2023-03-27 20:35 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/event/EventsState.java
> +public enum EventsState {
А зачем поменял?
Мне `EventState` больше нравилось, это же состояние одного конкретного события, а не некоторого подмножества событий

2023-03-27 20:35 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/user/UsersMapper.java
> +    }
Так лучше не делать. Если ты планируешь классы использовать по смыслу не только внутри каких-то классов, то лучше делать их отдельными классами.

Что я имею в виду:

1. Либо это три разных класса, которые лежат в разных файлах
2. Либо мы мапим, в том числе внутренние классы с помощью одного метода.

2023-03-27 20:35 UTC, LexLippi commented on ewm/src/main/resources/schema.sql
> +    EVENT_ID     BIGINT                      NOT NULL,
А это разве не внешние ключи?
Надо бы добавить `references`, и пометить их, как внешние ключи.

https://stackoverflow.com/questions/8595695/what-is-difference-between-foreign-key-and-reference-key

А еще неплохо было бы добавить индексы тем, колонкам по которым осущетвляется поиск:

https://climbtheladder.com/10-postgres-index-best-practices/

2023-03-27 21:57 UTC, FedoRScorpioN commented on ewm/src/main/java/ru/practicum/ewm/event/EventsState.java
> +public enum EventsState {
Добивался единообразия нейминга. Скорее всего это не всегда надо. Нужно исходить из сущности поведения?
Исправил.

2023-03-27 21:57 UTC, FedoRScorpioN commented on ewm/src/main/java/ru/practicum/ewm/user/UsersMapper.java
> +    }
Сделал второй вариант.

2023-03-27 22:15 UTC, FedoRScorpioN commented on ewm/src/main/resources/schema.sql
> +    EVENT_ID     BIGINT                      NOT NULL,
Добавил. Сделал индексирование Комментариев по Эвенту и Автору (думаю для комментариев это наиболее частые будут запросы.

2023-03-28 07:47 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Поздравляю с завершением обучения в Практикуме!

2023-03-28 17:45 UTC, merged